version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_boll
    environment:
      POSTGRES_USER: boll
      POSTGRES_PASSWORD: 110702
      POSTGRES_DB: bolldatabase
    ports:
      - "5432:5432"

